server:
  port: 8900


spring:
  application:
    name: chatting-service

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh, refresh, metrics

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true   # Registers the service using its IP address
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30